spring:
  application:
    name: ad-search
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate.format_sql: true
    open-in-view: false
  datasource:
    url: jdbc:mysql://123.56.16.37:3306/ad_data?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8
    username: admin
    password: 123qwe
    tomcat:
      max-active: 4
      min-idle: 2
      initial-size: 2
  jackson:
     date-format: yyyy-MM-dd HH:mm:ss
     time-zone: GMT+8
server:
  port: 7001
  servlet:
    context-path: /ad-search
eureka:
  client:
    service-url:
      defaultZone: http://server1:8001/eureka/
feign:
  hystrix:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
adconf:
  mysql:
    host: 123.56.16.37
    port: 3306
    username: admin
    password: 123qwe
    binlogName: ""
    position: -1
  kafka:
    topic: ad-search-mysql-data